import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import uuid from 'react-uuid';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { useAuth } from '../context/auth-context';

export default function Home() {
	const router = useRouter();
	const { setUserAuthInfo, currentToken } = useAuth();
	// const [currentToken, setCurrentToken] = useState('');

	// useEffect(() => {
	// 	setCurrentToken(localStorage.token !== 'undefined' && localStorage.token);
	// }, [authState.token]);

	return (
		<div className={styles.container}>
			<Head>
				<title>Protected Routes in NextJs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<br />
				{currentToken && <h2>{currentToken}</h2>}
				<br />
				<button onClick={() => setUserAuthInfo(uuid())}>Generate Token</button>
				<br />
				<button onClick={() => router.push('/dashboard')}>
					Go to Dashboard
				</button>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
